"""
core/cookie_wizard.py  –  Playwright-based cookie capture wizard
================================================================
Opens a headed, app-owned Chromium browser (never the user's real Chrome)
so the user can log in to a site, then captures and saves the session
cookies in Netscape format.

Uses a persistent profile (utils.paths.get_app_browser_profile_dir) so
Google's login/2FA/device-trust state survives across wizard runs — only
the exported cookies.txt needs refreshing when it expires.

Zero GUI imports — pure Python + Playwright.
Any UI dialogs (instructions, success/failure messages) must be shown
by the caller (e.g. ui/app_window.py) before and after this function.
"""

from __future__ import annotations

import logging
from pathlib import Path

from utils.paths import get_app_browser_profile_dir, get_app_cookies_path
from utils.playwright_check import (
    PlaywrightNotAvailable,
    require_playwright_or_raise,
)
from utils.security import redact_text, restrict_path_permissions, write_private_text

logger = logging.getLogger(__name__)


def format_netscape_cookies(cookies: list) -> str:
    """Convert a Playwright cookies list to Netscape-format string."""
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by BananaFlow",
        "",
    ]
    for c in cookies:
        domain      = c["domain"]
        include_sub = "TRUE" if domain.startswith(".") else "FALSE"
        path        = c["path"]
        secure      = "TRUE" if c["secure"] else "FALSE"
        expiry      = int(c.get("expires", 0))
        if expiry == -1:
            expiry = 0
        lines.append(
            f"{domain}\t{include_sub}\t{path}\t{secure}\t{expiry}\t{c['name']}\t{c['value']}"
        )
    return "\n".join(lines)


def run_cookie_wizard(start_url: str = "https://www.youtube.com") -> bool:
    """
    Launch a headed, app-owned Chromium browser for the user to log in.

    Uses a persistent profile (utils.paths.get_app_browser_profile_dir), so
    a signed-in session survives across calls — only re-login if Google
    actually invalidates the session, not on every wizard run.

    After the user closes the browser, captures all cookies and saves them
    to the standard app cookies path (~/.bananaflow/app_cookies.txt on Unix,
    %APPDATA%\\.bananaflow\\app_cookies.txt on Windows).

    Parameters
    ----------
    start_url :
        URL to navigate to on launch.  Falls back to YouTube home if it
        is not an HTTP(S) address (e.g. a yt-dlp ``ytsearch:`` string).

    Returns
    -------
    True  – cookies saved successfully.
    False – browser closed with no cookies, or an error occurred.

    Raises
    ------
    PlaywrightNotAvailable
        When Playwright Chromium is not installed. The caller should
        show a clear MessageBox using ``exc.message_en`` / ``message_he``
        instead of crashing.
    """
    require_playwright_or_raise("Sign-in / Cookie wizard")
    from playwright.sync_api import sync_playwright

    try:
        with sync_playwright() as p:
            profile_dir = get_app_browser_profile_dir()
            profile_dir.mkdir(parents=True, exist_ok=True)
            restrict_path_permissions(profile_dir, recursive=True)
            try:
                # channel="chrome" launches the user's real, installed Chrome
                # binary instead of Playwright's bundled Chromium-for-Testing
                # build. Google's login flow fingerprints that bundled build
                # (and the "--enable-automation" flag) and blocks sign-in
                # with "This browser or app may not be secure" — real Chrome
                # with that flag stripped avoids the block.
                context = p.chromium.launch_persistent_context(
                    str(profile_dir),
                    headless=False,
                    channel="chrome",
                    ignore_default_args=["--enable-automation"],
                )
            except Exception:
                # No system Chrome install found (e.g. Chrome-for-Testing-only
                # machine) — fall back to Playwright's bundled Chromium. Sign-in
                # to Google may then be blocked; that's the pre-existing
                # behavior, not a new regression.
                context = p.chromium.launch_persistent_context(
                    str(profile_dir), headless=False
                )

            # Stripping --enable-automation isn't enough on its own — Chrome
            # still reports navigator.webdriver=true to the page (a signal
            # Google's login flow checks), so mask it explicitly. This is a
            # single documented Playwright API call, not a third-party
            # "stealth" plugin (those are unmaintained and no longer reliable).
            context.add_init_script(
                "Object.defineProperty(navigator, 'webdriver', {get: () => undefined})"
            )

            page = context.pages[0] if context.pages else context.new_page()

            target = start_url if start_url.startswith("http") else "https://www.youtube.com"
            page.goto(target, wait_until="load")

            browser_closed = [False]

            def _on_close(*_args: object) -> None:
                browser_closed[0] = True

            page.on("close", _on_close)

            while not browser_closed[0]:
                try:
                    page.wait_for_timeout(1000)
                except Exception:
                    break

            cookies = context.cookies()

            try:
                context.close()
            except Exception:
                pass  # window is likely already closed by the user

            restrict_path_permissions(profile_dir, recursive=True)

            if not cookies:
                logger.warning("[CookieWizard] Browser closed with no cookies captured.")
                return False

            netscape_str = format_netscape_cookies(cookies)
            cookie_path: Path = get_app_cookies_path()
            write_private_text(cookie_path, netscape_str)

            logger.info("[CookieWizard] Saved %d cookies to %s", len(cookies), cookie_path)
            return True

    except Exception as exc:
        logger.error("[CookieWizard] Failed: %s", redact_text(exc))
        return False
