"""Minimal, private authentication-cookie storage.

Windows stores BananaFlow-owned Netscape cookie exports under current-user
DPAPI. Plaintext exists only in an owner-only temporary file while one
consumer is active. Other platforms retain the existing owner-only file model.
This module never reads a live browser profile.
"""

from __future__ import annotations

import ctypes
import logging
import os
import tempfile
import time
from contextlib import contextmanager
from pathlib import Path
from typing import Iterator

from utils.paths import (
    get_app_cookies_path,
    get_app_data_dir,
    get_legacy_app_cookies_path,
)
from utils.security import (
    harden_directory_once,
    restrict_path_permissions,
    write_private_bytes,
    write_private_text,
)

logger = logging.getLogger(__name__)

_WINDOWS = os.name == "nt"
DPAPI_MAGIC = b"BANANAFLOW-DPAPI\x00\x01"
_DPAPI_ENTROPY = b"BananaFlow/current-user/cookie-store/v1"
_COOKIES_HEADER = (
    "# Netscape HTTP Cookie File\n"
    "# Generated by BananaFlow; scoped to the minimum YouTube session set.\n\n"
)

# yt-dlp's YouTube extractor derives authenticated request hashes from
# SAPISID/1PAPISID/3PAPISID, uses LOGIN_INFO as the current-login marker,
# reads VISITOR_INFO1_LIVE as visitor data, and consumes PREF. The remaining
# names are YouTube session/privacy state needed by the web request itself.
# Broad Google account cookies such as SID, HSID, NID, AEC and 1P_JAR are
# deliberately excluded.
_COOKIE_NAMES = frozenset({
    "LOGIN_INFO",
    "SAPISID",
    "__Secure-1PAPISID",
    "__Secure-3PAPISID",
    "VISITOR_INFO1_LIVE",
    "VISITOR_PRIVACY_METADATA",
    "PREF",
    "YSC",
    "CONSENT",
    "SOCS",
    "DEVICE_INFO",
})
_COOKIE_DOMAIN_ROOTS = ("youtube.com", "google.com")


class CookieStoreError(OSError):
    """Stable failure with no cookie value or private path in its message."""


def _host(domain: str) -> str:
    return domain.removeprefix("#HttpOnly_").strip().lstrip(".").casefold()


def _allowed_domain(domain: str) -> bool:
    host = _host(domain)
    return any(host == root or host.endswith("." + root) for root in _COOKIE_DOMAIN_ROOTS)


def _cookie_entries(text: str) -> dict[tuple[str, str, str], str]:
    entries: dict[tuple[str, str, str], str] = {}
    now = int(time.time())
    for raw in (text or "").splitlines():
        line = raw.strip()
        if not line or (line.startswith("#") and not line.startswith("#HttpOnly_")):
            continue
        parts = line.split("\t")
        if len(parts) < 7:
            continue
        domain, cookie_path, expiry_raw, name = parts[0], parts[2], parts[4], parts[5]
        if not _allowed_domain(domain) or name not in _COOKIE_NAMES:
            continue
        try:
            expiry = int(expiry_raw)
        except (TypeError, ValueError):
            continue
        if expiry != 0 and expiry < now:
            continue
        entries[(domain, cookie_path, name)] = line
    return entries


def scoped_cookie_text(*sources: str) -> str:
    """Merge sources and retain only the current, minimal YouTube cookie set."""
    merged: dict[tuple[str, str, str], str] = {}
    for source in sources:
        merged.update(_cookie_entries(source))
    return _COOKIES_HEADER + "\n".join(merged.values()) + "\n"


class _DATA_BLOB(ctypes.Structure):
    _fields_ = [
        ("cbData", ctypes.c_ulong),
        ("pbData", ctypes.POINTER(ctypes.c_ubyte)),
    ]


def _input_blob(payload: bytes) -> tuple[_DATA_BLOB, ctypes.Array]:
    buffer = ctypes.create_string_buffer(payload, len(payload))
    blob = _DATA_BLOB(
        len(payload), ctypes.cast(buffer, ctypes.POINTER(ctypes.c_ubyte)),
    )
    return blob, buffer


def _protect_current_user(payload: bytes) -> bytes:
    """Protect bytes with current-user DPAPI, never machine-wide scope."""
    if not _WINDOWS:
        raise CookieStoreError("Windows current-user protection is unavailable.")
    crypt32 = ctypes.WinDLL("crypt32", use_last_error=True)
    kernel32 = ctypes.WinDLL("kernel32", use_last_error=True)
    source, source_buffer = _input_blob(payload)
    entropy, entropy_buffer = _input_blob(_DPAPI_ENTROPY)
    output = _DATA_BLOB()
    # Keep buffers alive until the native call returns.
    _ = source_buffer, entropy_buffer
    if not crypt32.CryptProtectData(
        ctypes.byref(source),
        "BananaFlow authentication cookies",
        ctypes.byref(entropy),
        None,
        None,
        0x1,  # CRYPTPROTECT_UI_FORBIDDEN; no LOCAL_MACHINE flag
        ctypes.byref(output),
    ):
        raise CookieStoreError("Authentication cookies could not be protected for this Windows account.")
    try:
        return ctypes.string_at(output.pbData, output.cbData)
    finally:
        kernel32.LocalFree(output.pbData)


def _unprotect_current_user(payload: bytes) -> bytes:
    if not _WINDOWS:
        raise CookieStoreError("This protected cookie store requires Windows.")
    crypt32 = ctypes.WinDLL("crypt32", use_last_error=True)
    kernel32 = ctypes.WinDLL("kernel32", use_last_error=True)
    source, source_buffer = _input_blob(payload)
    entropy, entropy_buffer = _input_blob(_DPAPI_ENTROPY)
    output = _DATA_BLOB()
    description = ctypes.c_wchar_p()
    _ = source_buffer, entropy_buffer
    if not crypt32.CryptUnprotectData(
        ctypes.byref(source),
        ctypes.byref(description),
        ctypes.byref(entropy),
        None,
        None,
        0x1,
        ctypes.byref(output),
    ):
        raise CookieStoreError("Stored authentication could not be decrypted for this Windows account.")
    try:
        return ctypes.string_at(output.pbData, output.cbData)
    finally:
        if description:
            kernel32.LocalFree(description)
        kernel32.LocalFree(output.pbData)


def write_cookie_store(path: str | Path, text: str) -> Path:
    """Filter and atomically store BananaFlow-owned authentication cookies."""
    destination = Path(path)
    payload = scoped_cookie_text(text).encode("utf-8")
    if _WINDOWS:
        return write_private_bytes(destination, DPAPI_MAGIC + _protect_current_user(payload))
    return write_private_text(destination, payload.decode("utf-8"))


def read_cookie_store(path: str | Path) -> str:
    """Read plaintext or a BananaFlow DPAPI store without exposing its path."""
    try:
        payload = Path(path).read_bytes()
    except OSError as exc:
        raise CookieStoreError("Stored authentication could not be read.") from exc
    if payload.startswith(DPAPI_MAGIC):
        payload = _unprotect_current_user(payload[len(DPAPI_MAGIC):])
    try:
        return payload.decode("utf-8")
    except UnicodeDecodeError as exc:
        raise CookieStoreError("Stored authentication has an invalid format.") from exc


def _private_temp_dir() -> Path:
    return get_app_data_dir() / "auth_tmp"


def _remove_temporary(path: Path) -> None:
    try:
        path.unlink()
        return
    except OSError:
        pass
    # Best-effort overwrite before a second deletion attempt. No path or
    # secret is logged if the operating system refuses cleanup.
    try:
        size = path.stat().st_size
        with path.open("r+b", buffering=0) as handle:
            handle.write(b"\x00" * size)
        path.unlink()
    except OSError:
        logger.warning("[CookieStore] A private temporary authentication file could not be removed")


@contextmanager
def materialize_cookie_file(source: str | Path | None) -> Iterator[str | None]:
    """Yield one private plaintext copy and delete it on every normal exit."""
    if not source or not Path(source).exists():
        yield str(source) if source else None
        return
    text = scoped_cookie_text(read_cookie_store(source))
    directory = _private_temp_dir()
    directory.mkdir(parents=True, exist_ok=True)
    harden_directory_once(directory)
    fd, raw_path = tempfile.mkstemp(prefix="session-", suffix=".txt", dir=directory)
    temporary = Path(raw_path)
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(text)
        restrict_path_permissions(temporary)
        yield str(temporary)
    finally:
        _remove_temporary(temporary)


def sweep_stale_cookie_temps() -> int:
    """Remove only BananaFlow-authored temp copies left by a prior crash."""
    directory = _private_temp_dir()
    if not directory.exists():
        return 0
    removed = 0
    for candidate in directory.glob("session-*.txt"):
        if not candidate.is_file():
            continue
        before = candidate.exists()
        _remove_temporary(candidate)
        if before and not candidate.exists():
            removed += 1
    return removed


def migrate_legacy_app_cookie_store(configured_path: str = "") -> str:
    """Encrypt an app-owned legacy plaintext export before deleting it."""
    if not _WINDOWS:
        return configured_path
    legacy = get_legacy_app_cookies_path()
    destination = get_app_cookies_path()
    try:
        configured = Path(configured_path).resolve() if configured_path else None
        legacy_resolved = legacy.resolve()
    except OSError:
        return configured_path
    if configured is not None and configured != legacy_resolved:
        return configured_path
    if not legacy.exists():
        return str(destination) if destination.exists() and configured is not None else configured_path
    try:
        expected = scoped_cookie_text(legacy.read_text(encoding="utf-8", errors="strict"))
        write_cookie_store(destination, expected)
        if read_cookie_store(destination) != expected:
            raise CookieStoreError("Protected authentication verification failed.")
        legacy.unlink()
        return str(destination)
    except (OSError, UnicodeError, CookieStoreError):
        logger.warning("[CookieStore] Legacy authentication storage could not be migrated safely")
        return configured_path
