"""
scripts/generate_constraints.py  –  Reviewed-environment constraints snapshot
==============================================================================
Phase 4 (reproducible builds / supply chain), section D. `requirements.txt`
and `pyproject.toml` intentionally keep floor (`>=`) version bounds so a
routine `pip install` always gets current fixes; that flexibility means two
installs on different days can resolve different exact versions. This
script captures the exact version of every installed package in a
known-good, isolated-gate-passing environment as a pip constraints file,
so a release build (or anyone debugging a regression) can reproduce that
same environment exactly:

    pip install -r requirements.txt -c constraints-windows-py312.txt

Regenerate this file whenever a dependency changes AND the isolated test
gate (scripts/run_isolated_tests.py) passes against the new environment —
never commit an unreviewed snapshot. `THIRD_PARTY_NOTICES.md`'s dependency
table and this file should agree; a mismatch means one of them is stale.

Usage:
    python scripts/generate_constraints.py [--out constraints-windows-py312.txt]
"""

from __future__ import annotations

import argparse
import sys
from datetime import datetime, timezone
from importlib import metadata
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out", default="constraints-windows-py312.txt",
        help="output constraints file path, relative to the repo root "
             "(default: constraints-windows-py312.txt)",
    )
    args = parser.parse_args()

    dists = sorted(metadata.distributions(), key=lambda d: (d.metadata.get("Name") or d.name).lower())
    lines = [
        f"# Generated by scripts/generate_constraints.py on "
        f"{datetime.now(timezone.utc).isoformat()}",
        f"# Python {sys.version.split()[0]} on {sys.platform}",
        "# Reviewed-environment snapshot — see the module docstring for how",
        "# to regenerate and when. Do not hand-edit; regenerate instead.",
        "",
    ]
    for dist in dists:
        name = dist.metadata.get("Name") or dist.name
        version = dist.version
        if not version:
            continue
        lines.append(f"{name}=={version}")

    out_path = REPO_ROOT / args.out
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {out_path} ({len(dists)} packages)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
