"""
packaging/stage_pot_provider.py  –  Stage the PO Token Provider for bundling
==============================================================================
Copies the ``bgutil-ytdlp-pot-provider`` plugin from the current
environment's site-packages into ``packaging/yt-dlp-plugins/``, in the
exact layout yt-dlp's own plugin loader expects next to the packaged EXE:

    packaging/yt-dlp-plugins/bgutil-ytdlp-pot-provider/
        yt_dlp_plugins/extractor/getpot_bgutil.py
        yt_dlp_plugins/extractor/getpot_bgutil_script.py

The public Windows package is PO-ready by default. This script stages
both parts required by the official yt-dlp Provider mechanism:

* the installed Python plugin package; and
* the matching upstream ``server/`` tree, installed for Deno script mode
  and passed to yt-dlp as ``youtubepot-bgutilscript:server_home``.

BananaFlow is GPL-3.0-or-later, and the bgutil provider is GPL v3, so this
is compatible for the GPL release. See packaging/yt-dlp-plugins/README.md
and THIRD_PARTY_NOTICES.md for license/source handling.

The staged files are regenerated by the build and are not committed to
git (see .gitignore). This script does not generate, scrape, store, or
inject PO Tokens itself; yt-dlp calls the provider through its official
plugin interface when YouTube extraction requires one.
"""

from __future__ import annotations

import hashlib
import importlib.metadata
import os
import shutil
import stat
import subprocess
import sys
import urllib.request
import zipfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent

DIST_NAME = "bgutil-ytdlp-pot-provider"
PROVIDER_VERSION = "1.3.1"
STAGING_ROOT = HERE / "yt-dlp-plugins" / DIST_NAME
BACKEND_ROOT = HERE / "pot-provider-backend" / DIST_NAME
SERVER_HOME = BACKEND_ROOT / "server"
DOWNLOAD_CACHE = HERE / "pot-provider-cache"
SOURCE_ZIP = DOWNLOAD_CACHE / f"{DIST_NAME}-{PROVIDER_VERSION}.zip"
SOURCE_URL = (
    "https://github.com/Brainicism/bgutil-ytdlp-pot-provider/archive/"
    f"refs/tags/{PROVIDER_VERSION}.zip"
)
# Verified before use so a compromised mirror/CDN or a corrupted transfer
# fails the build closed rather than staging an unverified GPL v3 backend.
# The upstream project's GitHub Release asset for this tag contains only the
# Python plugin (no server/ Deno backend tree), so it cannot replace this
# full-source archive -- this pin covers the archive/refs/tags/ URL below.
#
# The pin is over the archive's *contents*, not its bytes. GitHub generates
# /archive/refs/tags/*.zip on demand and does not guarantee the result is
# byte-stable: a change to its compression settings or archiving library
# produces a different zip containing identical files, and has done so before
# across the fleet. A byte pin would turn that into a build failure reading
# "SHA-256 mismatch ... refusing to stage" -- indistinguishable from a real
# compromise, and arriving without warning. Hashing what the archive contains
# is both stable across that and a stronger statement: it pins the source that
# actually gets staged, rather than one particular packaging of it.
#
# Keyed by version so a PROVIDER_VERSION bump without a matching pin fails
# immediately and loudly (the same shape scripts/fetch_deno_runtime.ps1 uses
# for Deno). Regenerate with:
#
#     python packaging/stage_pot_provider.py --print-tree-digest
#
PINNED_SOURCE_TREES = {
    "1.3.1": "6ce84380c5226d13cf096d7aea60ea9d015635b75abe7144d9104296d6ebc4ea",
}
SCRIPT_MODE_EXTRACTOR_FILES = {
    "getpot_bgutil.py",
    "getpot_bgutil_script.py",
}


def _remove_tree(path: Path) -> None:
    """Remove generated staging output, retrying read-only Windows files."""
    def _retry_writable(func, target, _exc_info):
        try:
            os.chmod(target, stat.S_IWRITE | stat.S_IREAD | stat.S_IEXEC)
        except OSError:
            pass
        func(target)

    shutil.rmtree(path, onerror=_retry_writable)


def stage() -> bool:
    """Copy the installed provider's yt_dlp_plugins/extractor/getpot_*.py
    files into packaging/yt-dlp-plugins/. Returns True on success, False
    if the package is missing from the current environment (prints a
    clear message either way)."""
    try:
        dist = importlib.metadata.distribution(DIST_NAME)
    except importlib.metadata.PackageNotFoundError:
        print(
            f"[stage_pot_provider] {DIST_NAME!r} is not installed in this "
            f"environment. The public Windows build requires this exact "
            f"plugin plus its Deno script backend. Install it first:\n"
            f"    pip install \"{DIST_NAME}=={PROVIDER_VERSION}\"\n"
            f"(or `pip install -e \".[po-token]\"`) before staging.",
            file=sys.stderr,
        )
        return False

    extractor_files = [
        f for f in (dist.files or ())
        if f.parts[:2] == ("yt_dlp_plugins", "extractor")
        and f.name.endswith(".py")
        and not f.name.startswith("_")
        and f.name in SCRIPT_MODE_EXTRACTOR_FILES
    ]
    if not extractor_files:
        print(
            f"[stage_pot_provider] {DIST_NAME!r} is installed but its RECORD "
            f"lists no script-mode yt_dlp_plugins/extractor/*.py files — "
            f"nothing to stage (package layout may have changed upstream).",
            file=sys.stderr,
        )
        return False
    staged_names = {f.name for f in extractor_files}
    missing = SCRIPT_MODE_EXTRACTOR_FILES - staged_names
    if missing:
        print(
            f"[stage_pot_provider] {DIST_NAME!r} is installed but is missing "
            f"required script-mode provider file(s): {', '.join(sorted(missing))}",
            file=sys.stderr,
        )
        return False

    dest_extractor_dir = STAGING_ROOT / "yt_dlp_plugins" / "extractor"
    if STAGING_ROOT.exists():
        _remove_tree(STAGING_ROOT)
    dest_extractor_dir.mkdir(parents=True, exist_ok=True)

    site_packages = Path(str(dist.locate_file("")))
    staged = []
    for rel_path in extractor_files:
        src = site_packages / rel_path
        dest = dest_extractor_dir / rel_path.name
        shutil.copy2(src, dest)
        staged.append(dest.name)

    try:
        staged_at = STAGING_ROOT.relative_to(ROOT)
    except ValueError:
        # STAGING_ROOT was monkeypatched outside ROOT (tests); fall back
        # to the absolute path rather than failing the whole run over a
        # log message.
        staged_at = STAGING_ROOT
    print(
        f"[stage_pot_provider] Staged {DIST_NAME} {dist.version} "
        f"({len(staged)} file(s): {', '.join(sorted(staged))}) into "
        f"{staged_at}"
    )
    return True


def _deno_path() -> Path:
    suffix = ".exe" if os.name == "nt" else ""
    return HERE / "runtime" / f"deno{suffix}"


def _npm_path() -> str:
    if os.name == "nt":
        return shutil.which("npm.cmd") or shutil.which("npm") or ""
    return shutil.which("npm") or ""


def _tree_digest_of(path: Path) -> str:
    """SHA-256 over what the archive *contains*, ignoring how it is packed.

    Digests ``<relative path>\\0<sha256 of contents>\\n`` for every file in the
    archive, sorted by path. Two zips holding identical files produce the same
    value regardless of compression level, member order, timestamps, or the
    tool that built them -- which is exactly the variability GitHub's
    on-demand tag archives exhibit and a byte-level hash cannot tolerate.

    Directory entries are skipped: they carry no content, and whether a zip
    records them at all is another packaging detail that differs between
    archivers.
    """
    digest = hashlib.sha256()
    with zipfile.ZipFile(path) as zf:
        members = sorted((m for m in zf.infolist() if not m.is_dir()),
                         key=lambda m: m.filename)
        for member in members:
            entry = hashlib.sha256()
            with zf.open(member) as f:
                for chunk in iter(lambda: f.read(1 << 20), b""):
                    entry.update(chunk)
            digest.update(member.filename.encode("utf-8"))
            digest.update(b"\0")
            digest.update(entry.hexdigest().encode("ascii"))
            digest.update(b"\n")
    return digest.hexdigest()


def _expected_tree_digest() -> str:
    """The pin for PROVIDER_VERSION, or a refusal if there is not one."""
    try:
        return PINNED_SOURCE_TREES[PROVIDER_VERSION]
    except KeyError:
        raise RuntimeError(
            f"[stage_pot_provider] No pinned source digest for {DIST_NAME} "
            f"{PROVIDER_VERSION}.\n"
            f"Verify the archive at {SOURCE_URL} (read the diff against the "
            f"previous tag, not just the hash), then record it:\n"
            f"    python packaging/stage_pot_provider.py --print-tree-digest\n"
            f"Refusing to stage an unpinned version rather than trusting "
            f"whatever the URL currently serves."
        ) from None


def _verify_source_archive(path: Path) -> None:
    """Fail closed on any mismatch -- a compromised mirror/CDN or a corrupted
    transfer must never be staged into the GPL v3 backend."""
    expected = _expected_tree_digest()
    try:
        actual = _tree_digest_of(path)
    except zipfile.BadZipFile as exc:
        path.unlink(missing_ok=True)
        raise RuntimeError(
            f"[stage_pot_provider] {path.name} is not a readable zip ({exc}). "
            f"Refusing to stage it; the cached copy has been removed so the "
            f"next run re-downloads."
        ) from None

    if actual != expected:
        path.unlink(missing_ok=True)
        raise RuntimeError(
            f"[stage_pot_provider] Source tree digest mismatch for {SOURCE_URL}\n"
            f"Expected: {expected}\n"
            f"Actual:   {actual}\n"
            f"This compares the archive's contents, not its bytes, so a "
            f"GitHub re-packaging cannot cause it -- the files themselves "
            f"differ from what was reviewed and pinned.\n"
            f"Refusing to stage an unverified {DIST_NAME} archive."
        )


def _download_source_archive() -> Path:
    # Resolve the pin before touching the network: an unpinned version must
    # fail without downloading anything.
    _expected_tree_digest()

    DOWNLOAD_CACHE.mkdir(parents=True, exist_ok=True)
    if SOURCE_ZIP.exists():
        _verify_source_archive(SOURCE_ZIP)
        return SOURCE_ZIP
    print(f"[stage_pot_provider] Downloading {SOURCE_URL}")
    urllib.request.urlretrieve(SOURCE_URL, SOURCE_ZIP)
    _verify_source_archive(SOURCE_ZIP)
    print(f"[stage_pot_provider] Source tree digest verified: "
          f"{_expected_tree_digest()}")
    return SOURCE_ZIP


def _copy_archive_member(zf: zipfile.ZipFile, member: zipfile.ZipInfo, dest: Path) -> None:
    dest.parent.mkdir(parents=True, exist_ok=True)
    with zf.open(member) as src, dest.open("wb") as out:
        shutil.copyfileobj(src, out)


def stage_backend() -> bool:
    """Stage upstream's Deno script backend and install prod dependencies."""
    deno = _deno_path()
    if not deno.exists():
        print(
            f"[stage_pot_provider] Bundled Deno runtime is required for "
            f"PO-ready packaging but was not found: {deno}",
            file=sys.stderr,
        )
        return False

    npm = _npm_path()
    if not npm:
        print(
            "[stage_pot_provider] npm is required at build time to install "
            "the provider backend's production node_modules tree from the "
            "upstream package-lock.json. Normal packaged users do not need "
            "Node/npm.",
            file=sys.stderr,
        )
        return False

    archive = _download_source_archive()
    archive_prefix = f"{DIST_NAME}-{PROVIDER_VERSION}/"
    staged_count = 0
    if BACKEND_ROOT.exists():
        _remove_tree(BACKEND_ROOT)
    with zipfile.ZipFile(archive) as zf:
        for member in zf.infolist():
            if member.is_dir() or not member.filename.startswith(archive_prefix):
                continue
            rel = member.filename[len(archive_prefix):]
            if not rel:
                continue
            rel_path = Path(rel)
            include = (
                rel_path.parts[0] == "server"
                or rel in {"LICENSE", "README.md", "CONTRIBUTING.md"}
            )
            if not include:
                continue
            _copy_archive_member(zf, member, BACKEND_ROOT / rel_path)
            staged_count += 1

    if not (SERVER_HOME / "src" / "generate_once.ts").exists():
        print(
            "[stage_pot_provider] Provider backend source archive did not "
            "contain server/src/generate_once.ts",
            file=sys.stderr,
        )
        return False

    env = os.environ.copy()
    env["DENO_DIR"] = str(DOWNLOAD_CACHE / "deno-cache")
    env["DENO_NO_PROMPT"] = "1"
    env["DENO_NO_UPDATE_CHECK"] = "1"
    env["FORCE_COLOR"] = "false"
    env["npm_config_audit"] = "false"
    env["npm_config_fund"] = "false"
    cmd = [
        npm,
        "ci",
        "--omit=dev",
    ]
    try:
        staged_at = SERVER_HOME.relative_to(ROOT)
    except ValueError:
        staged_at = SERVER_HOME
    print(
        f"[stage_pot_provider] Staged bgutil backend source "
        f"({staged_count} file(s)) into {staged_at}"
    )
    print("[stage_pot_provider] Installing backend production dependencies with npm")
    result = subprocess.run(cmd, cwd=SERVER_HOME, env=env, text=True)
    if result.returncode != 0:
        print(
            f"[stage_pot_provider] Deno dependency install failed "
            f"(exit {result.returncode})",
            file=sys.stderr,
        )
        return False

    script = SERVER_HOME / "src" / "generate_once.ts"
    node_modules = SERVER_HOME / "node_modules"
    if not script.exists() or not node_modules.is_dir():
        print(
            "[stage_pot_provider] Backend staging incomplete after npm install",
            file=sys.stderr,
        )
        return False

    try:
        script_at = script.relative_to(ROOT)
    except ValueError:
        script_at = script
    print(f"[stage_pot_provider] Provider backend ready: {script_at}")
    return True


def print_tree_digest() -> int:
    """Download the archive for PROVIDER_VERSION and print its tree digest.

    Deliberately does NOT verify against the pin — this is the tool you use to
    establish a pin for a new version, so it has to run before one exists.
    That also makes it the one path here that stages nothing: it downloads to
    the cache, prints, and stops. Review the upstream diff before trusting the
    number it gives you; the digest records what you accepted, it does not
    tell you whether accepting it was right.
    """
    DOWNLOAD_CACHE.mkdir(parents=True, exist_ok=True)
    if SOURCE_ZIP.exists():
        # Say so out loud. Pinning is the one operation where it matters
        # whether you are looking at what the URL serves now or at a copy of
        # unknown age sitting on this machine, and silently preferring the
        # cache would let a stale or tampered local file become the pin.
        print(f"[stage_pot_provider] Using the CACHED archive at {SOURCE_ZIP}",
              file=sys.stderr)
        print(f"[stage_pot_provider] Delete it and re-run to pin what "
              f"{SOURCE_URL} serves right now.", file=sys.stderr)
    else:
        print(f"[stage_pot_provider] Downloading {SOURCE_URL}", file=sys.stderr)
        urllib.request.urlretrieve(SOURCE_URL, SOURCE_ZIP)

    try:
        digest = _tree_digest_of(SOURCE_ZIP)
    except zipfile.BadZipFile as exc:
        print(f"[stage_pot_provider] {SOURCE_ZIP.name} is not a readable zip: {exc}",
              file=sys.stderr)
        SOURCE_ZIP.unlink(missing_ok=True)
        return 1

    print(f"# {SOURCE_URL}", file=sys.stderr)
    print(f'    "{PROVIDER_VERSION}": "{digest}",')
    return 0


if __name__ == "__main__":
    if "--print-tree-digest" in sys.argv[1:]:
        sys.exit(print_tree_digest())
    plugin_ok = stage()
    backend_ok = stage_backend() if plugin_ok else False
    sys.exit(0 if (plugin_ok and backend_ok) else 1)
